import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const RalewayFont = Raleway({
  variable: "--font-raleway",
  weight: "400",
  display: "swap", // <- helps avoid FOIT (flash of invisible text)
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${RalewayFont.variable} antialiased`}
      >
        {children}
        <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#000000",
                color: "#ffffff",
              },
            }}
          />
      </body>
    </html>
  );
}
